export default [{name : 'Broccoli', 
                url: 'https://m.media-amazon.com/images/I/61lxGX909uL._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Carrot', 
                url: 'https://m.media-amazon.com/images/I/81weI2ULFYL._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Corn', 
                url: 'https://m.media-amazon.com/images/I/71kb4tUZALL._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Cucumber', 
                url: 'https://m.media-amazon.com/images/I/71ob4ifemQL._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Eggplant', 
                url: 'https://m.media-amazon.com/images/I/71WSZsWgUvL._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Mushroom', 
                url: 'https://m.media-amazon.com/images/I/71XMKwfQCzL._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Onion', 
                url: 'https://m.media-amazon.com/images/I/51DJ-9xkuQL._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Peas', 
                url: 'https://m.media-amazon.com/images/I/41xZz3pFw6L._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Potato', 
                url: 'https://m.media-amazon.com/images/I/41QKCkQ2A5L._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Spinach', 
                url: 'https://m.media-amazon.com/images/I/71J4gpncRhL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Tomato', 
                url: 'https://m.media-amazon.com/images/I/61ZJhcdG7LL._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},
                {name : 'Turnips', 
                url: 'https://m.media-amazon.com/images/I/41EZjI5fjgL._AC_UL320_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"vegetable"},

                {name : 'Mango', 
                url: 'https://m.media-amazon.com/images/I/31cXlUcvRVL.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Lychee', 
                url: 'https://m.media-amazon.com/images/I/61KG35OByZL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Dragon Fruit', 
                url: 'https://m.media-amazon.com/images/I/71GsHTwUwaL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Dragon Fruit', 
                url: 'https://m.media-amazon.com/images/I/71GsHTwUwaL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Pear Green', 
                url: 'https://m.media-amazon.com/images/I/41YYLKLwOFL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Water Melon', 
                url: 'https://m.media-amazon.com/images/I/71ZaS7W9dYL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Apple Royal Gala', 
                url: 'https://m.media-amazon.com/images/I/81AK2aQ8VvL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Indian Cherry', 
                url: 'https://m.media-amazon.com/images/I/41WfimazUWL.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Papaya', 
                url: 'https://m.media-amazon.com/images/I/51N02i8rWuL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Jamun', 
                url: 'https://m.media-amazon.com/images/I/51mZcP005ZL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Pomegranates', 
                url: 'https://m.media-amazon.com/images/I/51I0L2K2L2L._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Banana', 
                url: 'https://m.media-amazon.com/images/I/51ebZJ+DR4L._SY342_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Kiwi', 
                url: 'https://m.media-amazon.com/images/I/815N83MFZwL._SL1500_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Orange', 
                url: 'https://m.media-amazon.com/images/I/51meUBlW2tL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Avocado', 
                url: 'https://m.media-amazon.com/images/I/71cs5TNn-LL._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"},
                {name : 'Guava', 
                url: 'https://m.media-amazon.com/images/I/51s1O0sVQ3L._SX679_.jpg',
                price: Math.floor(Math.random() *50)+1,
                category:"fruit"}                     
            
            
            
            ]